require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReservesController do

  # This should return the minimal set of attributes required to create a valid
  # Reserve. As you add validations to Reserve, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all reserves as @reserves" do
      reserve = Reserve.create! valid_attributes
      get :index
      assigns(:reserves).should eq([reserve])
    end
  end

  describe "GET show" do
    it "assigns the requested reserve as @reserve" do
      reserve = Reserve.create! valid_attributes
      get :show, :id => reserve.id
      assigns(:reserve).should eq(reserve)
    end
  end

  describe "GET new" do
    it "assigns a new reserve as @reserve" do
      get :new
      assigns(:reserve).should be_a_new(Reserve)
    end
  end

  describe "GET edit" do
    it "assigns the requested reserve as @reserve" do
      reserve = Reserve.create! valid_attributes
      get :edit, :id => reserve.id
      assigns(:reserve).should eq(reserve)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reserve" do
        expect {
          post :create, :reserve => valid_attributes
        }.to change(Reserve, :count).by(1)
      end

      it "assigns a newly created reserve as @reserve" do
        post :create, :reserve => valid_attributes
        assigns(:reserve).should be_a(Reserve)
        assigns(:reserve).should be_persisted
      end

      it "redirects to the created reserve" do
        post :create, :reserve => valid_attributes
        response.should redirect_to(Reserve.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reserve as @reserve" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reserve.any_instance.stub(:save).and_return(false)
        post :create, :reserve => {}
        assigns(:reserve).should be_a_new(Reserve)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reserve.any_instance.stub(:save).and_return(false)
        post :create, :reserve => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reserve" do
        reserve = Reserve.create! valid_attributes
        # Assuming there are no other reserves in the database, this
        # specifies that the Reserve created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reserve.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => reserve.id, :reserve => {'these' => 'params'}
      end

      it "assigns the requested reserve as @reserve" do
        reserve = Reserve.create! valid_attributes
        put :update, :id => reserve.id, :reserve => valid_attributes
        assigns(:reserve).should eq(reserve)
      end

      it "redirects to the reserve" do
        reserve = Reserve.create! valid_attributes
        put :update, :id => reserve.id, :reserve => valid_attributes
        response.should redirect_to(reserve)
      end
    end

    describe "with invalid params" do
      it "assigns the reserve as @reserve" do
        reserve = Reserve.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reserve.any_instance.stub(:save).and_return(false)
        put :update, :id => reserve.id, :reserve => {}
        assigns(:reserve).should eq(reserve)
      end

      it "re-renders the 'edit' template" do
        reserve = Reserve.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reserve.any_instance.stub(:save).and_return(false)
        put :update, :id => reserve.id, :reserve => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reserve" do
      reserve = Reserve.create! valid_attributes
      expect {
        delete :destroy, :id => reserve.id
      }.to change(Reserve, :count).by(-1)
    end

    it "redirects to the reserves list" do
      reserve = Reserve.create! valid_attributes
      delete :destroy, :id => reserve.id
      response.should redirect_to(reserves_url)
    end
  end

end
